version: "3.7"
networks:
  numberlink:
    name: numberlink

services:
  numberlink-ui:
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - numberlink

  ui-tunnel:
    image: kroniak/ssh-client
    restart: "always"
    command:
      - /bin/bash
      - -c
      - |
        ssh -oStrictHostKeyChecking=no -p 22222 -R numberlink.uetbc.xyz:80:numberlink-ui:3000 uetbc.xyz auto-close=true
    networks:
      - numberlink

